/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DespesaDAO;
import javax.swing.JOptionPane;
import model.Alimentacao;
import model.Despesa;
import model.Educacao;
import model.Lazer;
import model.Transporte;
import model.Vestuario;
import types.DespesaType;
import types.MessagesType;

/**
 *
 * @author amaranth.rosa
 */
public class Tela extends javax.swing.JFrame {

    private static Tela INSTANCE;

    public static Tela getInstance() {
        if (INSTANCE == null) {
            return INSTANCE = new Tela();
        }
        return INSTANCE;
    }

    /**
     * Creates new form Tela
     */
    public Tela() {
        DespesaDAO dao = DespesaDAO.getInstance();
        dao.load();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboTipo = new javax.swing.JComboBox<>();
        labelTitulo = new javax.swing.JLabel();
        inputValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonSave = new javax.swing.JButton();
        panelStatistics = new javax.swing.JPanel();
        alimentacaoLabel = new javax.swing.JLabel();
        educacaoLabel = new javax.swing.JLabel();
        lazerLabel = new javax.swing.JLabel();
        transporteLabel = new javax.swing.JLabel();
        vestuarioLabel = new javax.swing.JLabel();
        alimentacaoField = new javax.swing.JTextField();
        educacaoField = new javax.swing.JTextField();
        lazerField = new javax.swing.JTextField();
        transporteField = new javax.swing.JTextField();
        vestuarioField = new javax.swing.JTextField();
        buttonRegistrar = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentacao", "Educacao", "Lazer", "Transporte", "Vestuario" }));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTitulo.setText("Controle Financeiro");

        jLabel2.setText("Tipo");

        jLabel3.setText("Valor (R$):");

        buttonSave.setText("Salvar");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        alimentacaoLabel.setText("Alimentação:");

        educacaoLabel.setText("Educaçao:");

        lazerLabel.setText("Lazer:");

        transporteLabel.setText("Transporte:");

        vestuarioLabel.setText("Vestuário:");

        alimentacaoField.setEditable(false);

        educacaoField.setEditable(false);

        lazerField.setEditable(false);

        transporteField.setEditable(false);

        vestuarioField.setEditable(false);

        javax.swing.GroupLayout panelStatisticsLayout = new javax.swing.GroupLayout(panelStatistics);
        panelStatistics.setLayout(panelStatisticsLayout);
        panelStatisticsLayout.setHorizontalGroup(
            panelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatisticsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alimentacaoLabel)
                    .addComponent(educacaoLabel)
                    .addComponent(lazerLabel)
                    .addComponent(transporteLabel)
                    .addComponent(vestuarioLabel))
                .addGap(18, 18, 18)
                .addGroup(panelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alimentacaoField)
                    .addComponent(educacaoField)
                    .addComponent(lazerField)
                    .addComponent(transporteField)
                    .addComponent(vestuarioField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelStatisticsLayout.setVerticalGroup(
            panelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatisticsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alimentacaoLabel)
                    .addComponent(alimentacaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(educacaoLabel)
                    .addComponent(educacaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lazerLabel)
                    .addComponent(lazerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transporteLabel)
                    .addComponent(transporteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vestuarioLabel)
                    .addComponent(vestuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        buttonRegistrar.setText("Registrar");
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });

        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputValor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(buttonRegistrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSave)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addComponent(buttonRegistrar)
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSave)
                            .addComponent(buttonLimpar))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void refreshFields(Despesa despesa, DespesaType type) {
        DespesaDAO dao = DespesaDAO.getInstance();

        if (type.equals(DespesaType.ALIMENTACAO)) {
            alimentacaoField.setText(String.valueOf(dao.getTotalDespesaByTipo(despesa)));
        } else if (type.equals(DespesaType.EDUCACAO)) {
            educacaoField.setText(String.valueOf(dao.getTotalDespesaByTipo(despesa)));
        } else if (type.equals(DespesaType.LAZER)) {
            lazerField.setText(String.valueOf(dao.getTotalDespesaByTipo(despesa)));
        } else if (type.equals(DespesaType.TRANSPORTE)) {
            transporteField.setText(String.valueOf(dao.getTotalDespesaByTipo(despesa)));
        } else if (type.equals(DespesaType.VESTUARIO)) {
            vestuarioField.setText(String.valueOf(dao.getTotalDespesaByTipo(despesa)));
        }

    }

    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        DespesaDAO dao = DespesaDAO.getInstance();
        Despesa despesa = null;

        Double valueInput = 0.0;

        try {
            valueInput = Double.parseDouble(inputValor.getText());
        } catch (NumberFormatException nfe) {
            nfe.printStackTrace();
        }

        if (valueInput <= 0) {
            JOptionPane.showMessageDialog(null, MessagesType.DESPESA_CADASTRO_ERRO.getDescription());
        } else {

            if (String.valueOf(comboTipo.getSelectedItem()).equals(DespesaType.ALIMENTACAO.getDescription())) {
                despesa = new Alimentacao(valueInput);
                dao.addDesepsa(despesa);
                alimentacaoField.setText(String.valueOf(dao.getTotalDespesaByTipo(despesa)));

            } else if (String.valueOf(comboTipo.getSelectedItem()).equals(DespesaType.EDUCACAO.getDescription())) {
                despesa = new Educacao(valueInput);
                dao.addDesepsa(despesa);
                educacaoField.setText(String.valueOf(dao.getTotalDespesaByTipo(despesa)));

            } else if (String.valueOf(comboTipo.getSelectedItem()).equals(DespesaType.LAZER.getDescription())) {
                despesa = new Lazer(valueInput);
                dao.addDesepsa(despesa);
                lazerField.setText(String.valueOf(dao.getTotalDespesaByTipo(despesa)));

            } else if (String.valueOf(comboTipo.getSelectedItem()).equals(DespesaType.TRANSPORTE.getDescription())) {
                despesa = new Transporte(valueInput);
                dao.addDesepsa(despesa);
                transporteField.setText(String.valueOf(dao.getTotalDespesaByTipo(despesa)));

            } else if (String.valueOf(comboTipo.getSelectedItem()).equals(DespesaType.VESTUARIO.getDescription())) {
                despesa = new Vestuario(valueInput);
                dao.addDesepsa(despesa);
                vestuarioField.setText(String.valueOf(dao.getTotalDespesaByTipo(despesa)));

            }

        }


    }//GEN-LAST:event_buttonRegistrarActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        DespesaDAO dao = DespesaDAO.getInstance();
        dao.limpar();

        alimentacaoField.setText(null);
        educacaoField.setText(null);
        lazerField.setText(null);
        transporteField.setText(null);
        vestuarioField.setText(null);
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        DespesaDAO dao = DespesaDAO.getInstance();
        dao.save();

        JOptionPane.showMessageDialog(null, MessagesType.SALVO_SUCESSO.getDescription());
    }//GEN-LAST:event_buttonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alimentacaoField;
    private javax.swing.JLabel alimentacaoLabel;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JTextField educacaoField;
    private javax.swing.JLabel educacaoLabel;
    private javax.swing.JTextField inputValor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField lazerField;
    private javax.swing.JLabel lazerLabel;
    private javax.swing.JPanel panelStatistics;
    private javax.swing.JTextField transporteField;
    private javax.swing.JLabel transporteLabel;
    private javax.swing.JTextField vestuarioField;
    private javax.swing.JLabel vestuarioLabel;
    // End of variables declaration//GEN-END:variables
}
