/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ReservatorioDAO;
import javax.swing.JOptionPane;
import model.MaquinaCompensado;

/**
 *
 * @author amaranth.rosa
 */
public class TelaMaquina extends javax.swing.JFrame {

    private MaquinaCompensado maquina = new MaquinaCompensado();

    /**
     * Creates new form TelaMaquina
     */
    public TelaMaquina() {
        initComponents();

        MaquinaCompensado.criarReservatorios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonProduzirChapa = new javax.swing.JButton();
        buttonAbastecerCola = new javax.swing.JButton();
        buttonAbastecerCavacos = new javax.swing.JButton();
        labelPecas = new javax.swing.JLabel();
        fieldPecas = new javax.swing.JTextField();
        labelCola = new javax.swing.JLabel();
        fieldCola = new javax.swing.JTextField();
        labelCavacos = new javax.swing.JLabel();
        fieldCavacos = new javax.swing.JTextField();
        buttonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonZerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonProduzirChapa.setText("Produzir Chapa");
        buttonProduzirChapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProduzirChapaActionPerformed(evt);
            }
        });

        buttonAbastecerCola.setText("Abastecer cola");
        buttonAbastecerCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAbastecerColaActionPerformed(evt);
            }
        });

        buttonAbastecerCavacos.setText("Abastecer cavacos");
        buttonAbastecerCavacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAbastecerCavacosActionPerformed(evt);
            }
        });

        labelPecas.setText("Peças produzidas:");

        fieldPecas.setEnabled(false);

        labelCola.setText("Cola (litros):");

        fieldCola.setEnabled(false);

        labelCavacos.setText("Cavacos (m³):");

        fieldCavacos.setEnabled(false);

        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Máquina de Compensados");

        buttonZerar.setText("Zerar");
        buttonZerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonProduzirChapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAbastecerCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAbastecerCavacos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fieldCola)
                            .addComponent(fieldPecas)
                            .addComponent(labelPecas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCola, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCavacos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCavacos, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jLabel1))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(buttonZerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPecas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCavacos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldCavacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonProduzirChapa, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(buttonAbastecerCola, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonAbastecerCavacos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSair)
                    .addComponent(buttonZerar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProduzirChapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProduzirChapaActionPerformed
        maquina.produzirChapa();

      atualizarCampos();

    }//GEN-LAST:event_buttonProduzirChapaActionPerformed

    private void buttonAbastecerColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAbastecerColaActionPerformed
        String value = JOptionPane.showInputDialog("Informe quantidade (litros) - 600l MAX:");
        double vl = Double.parseDouble(value);

        maquina.abastecerCola(vl);
         atualizarCampos();
    }//GEN-LAST:event_buttonAbastecerColaActionPerformed

    private void buttonAbastecerCavacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAbastecerCavacosActionPerformed
        String value = JOptionPane.showInputDialog("Informe quantidade (m³) - 300m³ MAX:");
        double vl = Double.parseDouble(value);

        maquina.abastecerCavaco(vl);
        atualizarCampos();
    }//GEN-LAST:event_buttonAbastecerCavacosActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonZerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZerarActionPerformed

        maquina.zerarQuantidadeChapasProduzidas();
        
        atualizarCampos();

    }//GEN-LAST:event_buttonZerarActionPerformed

    public void atualizarCampos() {
        fieldPecas.setText(maquina.getQuantidadeChapasProduzidas());
        fieldCola.setText(maquina.getQuantidadeReservatorioCola());
        fieldCavacos.setText(maquina.getQuantidadeReservatorioCavacos());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMaquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbastecerCavacos;
    private javax.swing.JButton buttonAbastecerCola;
    private javax.swing.JButton buttonProduzirChapa;
    private javax.swing.JButton buttonSair;
    private javax.swing.JButton buttonZerar;
    private javax.swing.JTextField fieldCavacos;
    private javax.swing.JTextField fieldCola;
    private javax.swing.JTextField fieldPecas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCavacos;
    private javax.swing.JLabel labelCola;
    private javax.swing.JLabel labelPecas;
    // End of variables declaration//GEN-END:variables
}
