/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.LataDao;
import model.Lata;

import java.text.DecimalFormat;
import java.math.RoundingMode;
import javax.swing.JOptionPane;

/**
 *
 * @author amaranth.rosa
 */
public class Reciclonador2000 extends javax.swing.JFrame {

    private Lata lata;

    /**
     * Creates new form Reciclonador
     */
    public Reciclonador2000() {
        initComponents();

        LataDao dao = LataDao.getInstance();
        Lata lt = dao.load();

        if (lt != null) {
            this.lata = lt;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelRaio = new javax.swing.JLabel();
        inputRaio = new javax.swing.JTextField();
        labelAltura = new javax.swing.JLabel();
        inputAltura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldInfo = new javax.swing.JTextArea();
        buttonPoeLixo = new javax.swing.JButton();
        buttonTiraLixo = new javax.swing.JButton();
        buttonFecharSalvar = new javax.swing.JButton();
        buttonInfo = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonEsvaziar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Reciclonador 2000");

        labelRaio.setText("Raio:");

        labelAltura.setText("Altura:");

        fieldInfo.setColumns(20);
        fieldInfo.setRows(5);
        jScrollPane1.setViewportView(fieldInfo);

        buttonPoeLixo.setText("Põe Lixo");
        buttonPoeLixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPoeLixoActionPerformed(evt);
            }
        });

        buttonTiraLixo.setText("Tira Lixo");
        buttonTiraLixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTiraLixoActionPerformed(evt);
            }
        });

        buttonFecharSalvar.setText("Fechar & Salvar");
        buttonFecharSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharSalvarActionPerformed(evt);
            }
        });

        buttonInfo.setText("Atributos");
        buttonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInfoActionPerformed(evt);
            }
        });

        buttonUpdate.setText("Atualizar");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonEsvaziar.setText("Esvaziar");
        buttonEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEsvaziarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1)
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonEsvaziar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonFecharSalvar)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonTiraLixo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonPoeLixo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAltura)
                            .addComponent(labelRaio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputRaio, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(inputAltura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonUpdate))
                            .addComponent(jScrollPane1))
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRaio)
                            .addComponent(inputRaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAltura)
                            .addComponent(inputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonInfo)
                            .addComponent(buttonUpdate))
                        .addGap(8, 8, 8)
                        .addComponent(buttonPoeLixo)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTiraLixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFecharSalvar)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonEsvaziar)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setFieldInfoData(Lata lata) {
        DecimalFormat df = new DecimalFormat("#.##");
        df.setRoundingMode(RoundingMode.DOWN);

        try {

            String info = "Altura: " + lata.getAltura() + " cm"
                    + "\nRaio: " + lata.getRaio() + " cm"
                    + "\nÁrea base: " + df.format(lata.getAreaBase()) + " cm²"
                    + "\nVolume: " + df.format(lata.getVolume()) + " cm³"
                    + "\nQt. Lixo: " + lata.getQtLixo() + " un"
                    + "\nCheia? " + lata.textoLixeiraCheia();
            fieldInfo.setText(info);

        } catch (NumberFormatException nfe) {
            nfe.printStackTrace();
        }

    }

    private void buttonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInfoActionPerformed

        if (this.lata == null) {

            JOptionPane.showMessageDialog(null, "Objeto não registrado na memória, criando novo componente...");

            String raio = inputRaio.getText();
            String altura = inputAltura.getText();

            double r = Double.parseDouble(raio);
            double a = Double.parseDouble(altura);

            Lata lata = new Lata(a, r);
            lata.setAreaBase(lata.calcularAreaBase());
            lata.setVolume(lata.calcularVolume());

            this.lata = lata;

        } else {

            JOptionPane.showMessageDialog(null, "Objeto já existente... recuperando da memória...");

        }

        setFieldInfoData(lata);

    }//GEN-LAST:event_buttonInfoActionPerformed

    private void buttonFecharSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharSalvarActionPerformed
        LataDao dao = LataDao.getInstance();
        dao.save(this.lata);

        System.exit(0);
    }//GEN-LAST:event_buttonFecharSalvarActionPerformed

    private void buttonPoeLixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPoeLixoActionPerformed
        this.lata.poeLixo();
        setFieldInfoData(lata);
    }//GEN-LAST:event_buttonPoeLixoActionPerformed

    private void buttonTiraLixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTiraLixoActionPerformed
        this.lata.tiraLixo();
        setFieldInfoData(lata);
    }//GEN-LAST:event_buttonTiraLixoActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        Lata lt = this.lata;

        if (lt != null) {
            double r = Double.parseDouble(inputRaio.getText());
            double a = Double.parseDouble(inputAltura.getText());

            lt.setAreaBase(lt.calcularAreaBase());
            lt.setVolume(lt.calcularVolume());

            this.lata = lt;
        }

        setFieldInfoData(lt);
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEsvaziarActionPerformed
        this.lata.esvaziaLixo();
        this.lata.setCheia(false);
        setFieldInfoData(lata);
    }//GEN-LAST:event_buttonEsvaziarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reciclonador2000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reciclonador2000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reciclonador2000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reciclonador2000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reciclonador2000().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEsvaziar;
    private javax.swing.JButton buttonFecharSalvar;
    private javax.swing.JButton buttonInfo;
    private javax.swing.JButton buttonPoeLixo;
    private javax.swing.JButton buttonTiraLixo;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JTextArea fieldInfo;
    private javax.swing.JTextField inputAltura;
    private javax.swing.JTextField inputRaio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelRaio;
    // End of variables declaration//GEN-END:variables
}
